FILEPATH0 = /Users/ollesvensson/DevFiles/reg-duplicates/CXC/Rgn00.txt
FILEPATH1 = /Users/ollesvensson/DevFiles/reg-duplicates/CXC/Rgn01.txt
FILEPATH2 = /Users/ollesvensson/DevFiles/reg-duplicates/CXC/Rgn02.txt

all:
	make build
	make run0

build: Main.java
	javac Main.java

run0:
	java Main $(FILEPATH0)

run1:
	java Main $(FILEPATH1)

run2:
	java Main $(FILEPATH2)


